// systemd units of the server backup job (docs/server.md "Backup"). One property list serves
// the service unit and `systemd-run` (a root shell running a store-touching backup verb runs it
// with exactly the unit's user, credentials and sandbox).

import { join } from "node:path";

import { CREDENTIAL_FILES } from "./restic.mjs";

export const BACKUP_SERVICE_PATH = "/etc/systemd/system/kuma-vault-backup.service";
export const BACKUP_TIMER_PATH = "/etc/systemd/system/kuma-vault-backup.timer";
// 04:30 KST, an hour after the Mac routine (30 3 * * *): prune takes restic's exclusive lock
export const BACKUP_ON_CALENDAR = "*-*-* 04:30:00 Asia/Seoul";

export function backupServiceProperties({ configPath, dataDir, credentialsDir, nodeBin, user }) {
  return [
    `User=${user}`,
    `Group=${user}`,
    `Environment=PATH=${nodeBin}:/usr/local/bin:/usr/bin:/bin`,
    `Environment=KUMA_VAULT_SERVER_CONFIG=${configPath}`,
    ...Object.values(CREDENTIAL_FILES).map((name) => `LoadCredential=${name}:${join(credentialsDir, name)}`),
    "CacheDirectory=kuma-vault-backup",
    "Nice=10",
    "IOSchedulingClass=idle",
    "NoNewPrivileges=true",
    "PrivateTmp=true",
    "ProtectHome=true",
    "ProtectSystem=strict",
    `ReadWritePaths=${dataDir}`,
  ];
}

export function renderBackupService({ configPath, dataDir, credentialsDir, nodeBin, user, engineBase }) {
  return [
    "# kuma-vault backup — generated by `vault server install` (docs/server.md \"Backup\")",
    "[Unit]",
    "Description=kuma-vault backup (restic, this host's snapshots only)",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=oneshot",
    ...backupServiceProperties({ configPath, dataDir, credentialsDir, nodeBin, user }),
    `ExecStart=${engineBase}/current/bin/vault server backup nightly --config ${configPath}`,
    "TimeoutStartSec=12h",
    "",
  ].join("\n");
}

export function renderBackupTimer() {
  return [
    "# kuma-vault backup timer — generated by `vault server install` (docs/server.md \"Backup\")",
    "[Unit]",
    "Description=kuma-vault nightly backup",
    "",
    "[Timer]",
    `OnCalendar=${BACKUP_ON_CALENDAR}`,
    "Persistent=true",
    "",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n");
}
