// `vault server install` — run as root on the server,
// from an engine checkout unpacked at /opt/kuma-vault/<version>/. bin/vault has already put
// Node 22 at /opt/node/current (it needs Node to reach this file). This part:
//
//   git-lfs, restic (apt) · system user kuma-vault · <dataDir> 0750 · /etc/kuma-vault/server.json
//   (0600, created once, validated after) · stores (--store) · /opt/kuma-vault/current -> this
//   checkout · kuma-vault-serve.service (enabled, restarted) · health check on loopback ·
//   kuma-vault-backup.service + .timer (timer enabled only when server.json has a backup block).
//   `--auth token` (a server behind an HTTPS reverse proxy, no tailnet): the first server.json gets
//   `auth.mode: "token"` and listens on loopback only.
//
// Idempotent: re-running repairs what is missing and never overwrites an existing server.json.

import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, chownSync, existsSync, mkdirSync, readlinkSync, renameSync, rmSync, symlinkSync, writeFileSync, realpathSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { BACKUP_SERVICE_PATH, BACKUP_TIMER_PATH, renderBackupService, renderBackupTimer } from "./backup-units.mjs";
import { DEFAULT_BACKUP_CREDENTIALS_DIR, DEFAULT_PORT, DEFAULT_SERVER_CONFIG_PATH, loadServerConfig, normalizeServerConfig, parseListenAddress, writeServerConfig } from "./server-config.mjs";
import { initStore } from "./store-layout.mjs";

const PKG_ROOT = realpathSync(join(dirname(fileURLToPath(import.meta.url)), "..", ".."));
export const SERVICE_USER = "kuma-vault";
export const ENGINE_BASE = "/opt/kuma-vault";
export const NODE_CURRENT = "/opt/node/current";
export const UNIT_PATH = "/etc/systemd/system/kuma-vault-serve.service";

function say(line) {
  process.stdout.write(`${line}\n`);
}

function run(cmd, args, { allowFail = false } = {}) {
  const result = spawnSync(cmd, args, { encoding: "utf8" });
  if (result.error) throw new Error(`${cmd} ${args.join(" ")}: ${result.error.message}`);
  if (result.status !== 0 && !allowFail) {
    throw new Error(`${cmd} ${args.join(" ")} failed (${result.status}): ${(result.stderr || result.stdout).trim()}`);
  }
  return result;
}

function idOf(kind, name) {
  return Number(execFileSync("id", [kind, name], { encoding: "utf8" }).trim());
}

function chownTree(path, uid, gid) {
  run("chown", ["-R", `${uid}:${gid}`, path]);
}

/** uid/gid of the serve user; missing before the first `vault server install`. */
export function serveUserIds() {
  if (run("getent", ["passwd", SERVICE_USER], { allowFail: true }).status !== 0) {
    throw new Error(`no ${SERVICE_USER} user on this machine — run \`sudo vault server install\` first`);
  }
  return { uid: idOf("-u", SERVICE_USER), gid: idOf("-g", SERVICE_USER) };
}

/** Refuse when this process could not hand a store to `owner` (not root, and not that user). */
export function requireStoreOwnable(owner) {
  const uid = process.getuid?.();
  if (uid !== undefined && uid !== 0 && uid !== owner.uid) {
    throw new Error(`a store must belong to uid ${owner.uid} (${SERVICE_USER}); run this as root (sudo)`);
  }
}

/**
 * Create (or repair) a store and give its whole tree to the serve user, which runs serve and the
 * hooks — install and `vault server init-store` both.
 */
export async function initServedStore(path, { vaultBin, owner }) {
  requireStoreOwnable(owner);
  const paths = await initStore(path, { vaultBin });
  chownTree(path, owner.uid, owner.gid);
  return paths;
}

export function renderUnit({ configPath }) {
  return [
    "# kuma-vault serve — generated by `vault server install` (docs/server.md)",
    "[Unit]",
    "Description=kuma-vault serve (git smart HTTP + LFS for vault stores)",
    "After=network-online.target tailscaled.service",
    "Wants=network-online.target tailscaled.service",
    "",
    "[Service]",
    `User=${SERVICE_USER}`,
    `Group=${SERVICE_USER}`,
    `Environment=PATH=${NODE_CURRENT}/bin:/usr/local/bin:/usr/bin:/bin`,
    `Environment=KUMA_VAULT_SERVER_CONFIG=${configPath}`,
    `ExecStart=${ENGINE_BASE}/current/bin/vault serve --config ${configPath}`,
    "Restart=always",
    "RestartSec=5",
    "NoNewPrivileges=true",
    "PrivateTmp=true",
    "ProtectHome=true",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

function defaultListen() {
  const result = run("tailscale", ["ip", "-4"], { allowFail: true });
  const ip = result.status === 0 ? result.stdout.trim().split("\n")[0] : "";
  if (!ip) throw new Error("tailscale ip -4 gave no address — bring tailscale up first, or pass --listen <ip:port,...>");
  return [`${ip}:${DEFAULT_PORT}`, `127.0.0.1:${DEFAULT_PORT}`];
}

function listOption(value) {
  if (value === undefined || value === true) return [];
  return String(value).split(",").map((s) => s.trim()).filter(Boolean);
}

async function waitForHealth(port, timeoutMs = 20_000) {
  const deadline = Date.now() + timeoutMs;
  let last = null;
  while (Date.now() < deadline) {
    try {
      const response = await fetch(`http://127.0.0.1:${port}/v1/health`);
      if (response.ok) return response.json();
      last = `HTTP ${response.status}`;
    } catch (error) {
      last = error.message;
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`serve did not answer health on 127.0.0.1:${port} within ${timeoutMs / 1000}s (${last}) — see journalctl -u kuma-vault-serve`);
}

/** Backup unit + timer. The credential directory is root-only 0700. */
function installBackupUnits({ config, configPath }) {
  const credentialsDir = config.backup?.credentialsDir ?? DEFAULT_BACKUP_CREDENTIALS_DIR;
  mkdirSync(credentialsDir, { recursive: true, mode: 0o700 });
  chmodSync(credentialsDir, 0o700);
  chownSync(credentialsDir, 0, 0);
  const service = renderBackupService({ configPath, dataDir: config.dataDir, credentialsDir, nodeBin: join(NODE_CURRENT, "bin"), user: SERVICE_USER, engineBase: ENGINE_BASE });
  writeFileSync(BACKUP_SERVICE_PATH, service, { mode: 0o644 });
  writeFileSync(BACKUP_TIMER_PATH, renderBackupTimer(), { mode: 0o644 });
  say(`wrote ${BACKUP_SERVICE_PATH}, ${BACKUP_TIMER_PATH} (credentials: ${credentialsDir}, root 0700)`);
}

export async function commandServerInstall(options) {
  if (process.getuid?.() !== 0) throw new Error("vault server install must run as root (sudo)");
  const configPath = options.config ?? DEFAULT_SERVER_CONFIG_PATH;
  const dataDir = options["data-dir"] ?? "/data/vaults";
  const stores = listOption(options.store);
  const owners = listOption(options.owner);
  const authMode = options.auth === undefined ? null : String(options.auth);
  if (authMode !== null && authMode !== "tailscale" && authMode !== "token") throw new Error(`--auth must be tailscale or token (got "${authMode}")`);

  // engine checkout location (/opt/kuma-vault/<version>, current -> symlink)
  if (dirname(PKG_ROOT) !== ENGINE_BASE || basename(PKG_ROOT) === "current") {
    throw new Error(`run install from an engine checkout unpacked at ${ENGINE_BASE}/<version>/ (this one is ${PKG_ROOT})`);
  }
  if (!existsSync(join(NODE_CURRENT, "bin", "node"))) throw new Error(`${NODE_CURRENT}/bin/node missing — bin/vault bootstraps it; run via ${PKG_ROOT}/bin/vault server install`);

  run("git", ["--version"]);
  if (run("git", ["lfs", "version"], { allowFail: true }).status !== 0) {
    say("installing git-lfs (apt)");
    run("apt-get", ["install", "-y", "git-lfs"]);
  }
  if (run("restic", ["version"], { allowFail: true }).status !== 0) {
    say("installing restic (apt)");
    run("apt-get", ["install", "-y", "restic"]);
  }

  if (run("getent", ["passwd", SERVICE_USER], { allowFail: true }).status !== 0) {
    say(`creating system user ${SERVICE_USER}`);
    run("useradd", ["--system", "--user-group", "--home-dir", dataDir, "--no-create-home", "--shell", "/usr/sbin/nologin", SERVICE_USER]);
  }
  const uid = idOf("-u", SERVICE_USER);
  const gid = idOf("-g", SERVICE_USER);

  mkdirSync(dataDir, { recursive: true, mode: 0o750 });
  chmodSync(dataDir, 0o750);
  chownSync(dataDir, uid, gid);

  const configDir = dirname(configPath);
  mkdirSync(configDir, { recursive: true, mode: 0o750 });
  chmodSync(configDir, 0o750);
  chownSync(configDir, 0, gid);

  let config;
  if (existsSync(configPath)) {
    config = loadServerConfig(configPath);
    say(`server.json exists, validated: ${configPath}`);
    if (authMode !== null && config.auth.mode !== authMode) {
      throw new Error(`${configPath} has auth.mode "${config.auth.mode}"; install never rewrites server.json — edit auth.mode there, then run install again`);
    }
  } else {
    const listen = listOption(options.listen);
    // token mode sits behind a reverse proxy on this machine: loopback only, no tailnet needed
    const defaults = authMode === "token" ? [`127.0.0.1:${DEFAULT_PORT}`] : null;
    config = normalizeServerConfig({
      version: 1,
      listen: listen.length ? listen : defaults ?? defaultListen(),
      dataDir,
      stores: {},
      ...(authMode === "token" ? { auth: { mode: "token" } } : {}),
    });
    writeServerConfig(configPath, config);
    say(`wrote ${configPath} (auth ${config.auth.mode}, listen ${config.listen.join(", ")})`);
  }
  for (const id of stores) {
    if (!config.stores[id]) {
      config = writeServerConfig(configPath, {
        ...config,
        stores: { ...config.stores, [id]: { kind: "vault", owners, writers: [], readers: [], binaries: { reject: [] }, encryption: null } },
      });
      say(`added store ${id} to server.json (owners: ${owners.join(", ") || "none — add logins or tokens"})`);
    }
  }
  chownSync(configPath, uid, gid);
  chmodSync(configPath, 0o600);

  // engine `current` symlink, swapped atomically
  const current = join(ENGINE_BASE, "current");
  let currentTarget = null;
  try {
    currentTarget = readlinkSync(current);
  } catch {
    currentTarget = null;
  }
  if (currentTarget !== PKG_ROOT && currentTarget !== basename(PKG_ROOT)) {
    const temp = `${current}.${process.pid}`;
    rmSync(temp, { force: true });
    symlinkSync(PKG_ROOT, temp);
    renameSync(temp, current);
    say(`${current} -> ${PKG_ROOT}`);
  }

  const vaultBin = join(current, "bin", "vault");
  for (const [id, store] of Object.entries(config.stores)) {
    await initServedStore(store.path, { vaultBin, owner: { uid, gid } });
    say(`store ${id}: ${store.path}`);
  }

  writeFileSync(UNIT_PATH, renderUnit({ configPath }), { mode: 0o644 });
  installBackupUnits({ config, configPath });
  if (options["no-start"]) {
    run("systemctl", ["daemon-reload"]);
    say(`wrote ${UNIT_PATH} (not started: --no-start)`);
    return;
  }
  run("systemctl", ["daemon-reload"]);
  if (config.backup) {
    run("systemctl", ["enable", "--now", "kuma-vault-backup.timer"]);
    say(`backup timer enabled (${config.backup.host} -> ${config.backup.repository.replace(/[0-9a-f]{32}/g, "<account>")})`);
  } else {
    run("systemctl", ["disable", "--now", "kuma-vault-backup.timer"], { allowFail: true });
    say("backup not configured: kuma-vault-backup.timer left disabled (vault server backup configure, then install again)");
  }
  run("systemctl", ["enable", "kuma-vault-serve.service"]);
  run("systemctl", ["restart", "kuma-vault-serve.service"]);
  const loopback = config.listen.map(parseListenAddress).find((l) => l.host === "127.0.0.1");
  if (!loopback) {
    say("serve started (no 127.0.0.1 listen address, health not checked)");
    return;
  }
  const health = await waitForHealth(loopback.port);
  say(`serve healthy: version ${health.version}, /data free ${health.diskFreeGB}GB, diskAlert ${health.diskAlert ?? "none"}`);
}
